// Code generated by protoc-gen-go.
// source: hapi/modules/release.proto
// DO NOT EDIT!

/*
Package release is a generated protocol buffer package.

It is generated from these files:
	hapi/modules/release.proto

It has these top-level messages:
	Result
	InstallReleaseRequest
	InstallReleaseResponse
	DeleteReleaseRequest
	DeleteReleaseResponse
	UpgradeReleaseRequest
	UpgradeReleaseResponse
	RollbackReleaseRequest
	RollbackReleaseResponse
*/
package release

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_release3 "hapi/release"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result_Status int32

const (
	// No status set
	Result_UNKNOWN Result_Status = 0
	// Operation was successful
	Result_SUCCESS Result_Status = 1
	// Operation had no results (e.g. upgrade identical, rollback to same, delete non-existent)
	Result_UNCHANGED Result_Status = 2
	// Operation failed
	Result_ERROR Result_Status = 3
)

var Result_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "UNCHANGED",
	3: "ERROR",
}
var Result_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"SUCCESS":   1,
	"UNCHANGED": 2,
	"ERROR":     3,
}

func (x Result_Status) String() string {
	return proto.EnumName(Result_Status_name, int32(x))
}
func (Result_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Result struct {
	Info string   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Log  []string `protobuf:"bytes,2,rep,name=log" json:"log,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InstallReleaseRequest struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *InstallReleaseRequest) Reset()                    { *m = InstallReleaseRequest{} }
func (m *InstallReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseRequest) ProtoMessage()               {}
func (*InstallReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InstallReleaseRequest) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type InstallReleaseResponse struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result                `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *InstallReleaseResponse) Reset()                    { *m = InstallReleaseResponse{} }
func (m *InstallReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*InstallReleaseResponse) ProtoMessage()               {}
func (*InstallReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InstallReleaseResponse) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *InstallReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteReleaseRequest struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *DeleteReleaseRequest) Reset()                    { *m = DeleteReleaseRequest{} }
func (m *DeleteReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteReleaseRequest) ProtoMessage()               {}
func (*DeleteReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteReleaseRequest) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type DeleteReleaseResponse struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result                `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *DeleteReleaseResponse) Reset()                    { *m = DeleteReleaseResponse{} }
func (m *DeleteReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteReleaseResponse) ProtoMessage()               {}
func (*DeleteReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteReleaseResponse) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *DeleteReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpgradeReleaseRequest struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *UpgradeReleaseRequest) Reset()                    { *m = UpgradeReleaseRequest{} }
func (m *UpgradeReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpgradeReleaseRequest) ProtoMessage()               {}
func (*UpgradeReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpgradeReleaseRequest) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type UpgradeReleaseResponse struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result                `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *UpgradeReleaseResponse) Reset()                    { *m = UpgradeReleaseResponse{} }
func (m *UpgradeReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpgradeReleaseResponse) ProtoMessage()               {}
func (*UpgradeReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpgradeReleaseResponse) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *UpgradeReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type RollbackReleaseRequest struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *RollbackReleaseRequest) Reset()                    { *m = RollbackReleaseRequest{} }
func (m *RollbackReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseRequest) ProtoMessage()               {}
func (*RollbackReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RollbackReleaseRequest) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type RollbackReleaseResponse struct {
	Release *hapi_release3.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Result  *Result                `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *RollbackReleaseResponse) Reset()                    { *m = RollbackReleaseResponse{} }
func (m *RollbackReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackReleaseResponse) ProtoMessage()               {}
func (*RollbackReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RollbackReleaseResponse) GetRelease() *hapi_release3.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *RollbackReleaseResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "hapi.modules.Result")
	proto.RegisterType((*InstallReleaseRequest)(nil), "hapi.modules.InstallReleaseRequest")
	proto.RegisterType((*InstallReleaseResponse)(nil), "hapi.modules.InstallReleaseResponse")
	proto.RegisterType((*DeleteReleaseRequest)(nil), "hapi.modules.DeleteReleaseRequest")
	proto.RegisterType((*DeleteReleaseResponse)(nil), "hapi.modules.DeleteReleaseResponse")
	proto.RegisterType((*UpgradeReleaseRequest)(nil), "hapi.modules.UpgradeReleaseRequest")
	proto.RegisterType((*UpgradeReleaseResponse)(nil), "hapi.modules.UpgradeReleaseResponse")
	proto.RegisterType((*RollbackReleaseRequest)(nil), "hapi.modules.RollbackReleaseRequest")
	proto.RegisterType((*RollbackReleaseResponse)(nil), "hapi.modules.RollbackReleaseResponse")
	proto.RegisterEnum("hapi.modules.Result_Status", Result_Status_name, Result_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ReleaseModuleService service

type ReleaseModuleServiceClient interface {
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error)
	// DeleteRelease requests deletion of a named release.
	DeleteRelease(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error)
	// UpgradeRelease updates release content.
	UpgradeRelease(ctx context.Context, in *UpgradeReleaseRequest, opts ...grpc.CallOption) (*UpgradeReleaseResponse, error)
}

type releaseModuleServiceClient struct {
	cc *grpc.ClientConn
}

func NewReleaseModuleServiceClient(cc *grpc.ClientConn) ReleaseModuleServiceClient {
	return &releaseModuleServiceClient{cc}
}

func (c *releaseModuleServiceClient) InstallRelease(ctx context.Context, in *InstallReleaseRequest, opts ...grpc.CallOption) (*InstallReleaseResponse, error) {
	out := new(InstallReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.modules.ReleaseModuleService/InstallRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) DeleteRelease(ctx context.Context, in *DeleteReleaseRequest, opts ...grpc.CallOption) (*DeleteReleaseResponse, error) {
	out := new(DeleteReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.modules.ReleaseModuleService/DeleteRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) RollbackRelease(ctx context.Context, in *RollbackReleaseRequest, opts ...grpc.CallOption) (*RollbackReleaseResponse, error) {
	out := new(RollbackReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.modules.ReleaseModuleService/RollbackRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *releaseModuleServiceClient) UpgradeRelease(ctx context.Context, in *UpgradeReleaseRequest, opts ...grpc.CallOption) (*UpgradeReleaseResponse, error) {
	out := new(UpgradeReleaseResponse)
	err := grpc.Invoke(ctx, "/hapi.modules.ReleaseModuleService/UpgradeRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReleaseModuleService service

type ReleaseModuleServiceServer interface {
	// InstallRelease requests installation of a chart as a new release.
	InstallRelease(context.Context, *InstallReleaseRequest) (*InstallReleaseResponse, error)
	// DeleteRelease requests deletion of a named release.
	DeleteRelease(context.Context, *DeleteReleaseRequest) (*DeleteReleaseResponse, error)
	// RollbackRelease rolls back a release to a previous version.
	RollbackRelease(context.Context, *RollbackReleaseRequest) (*RollbackReleaseResponse, error)
	// UpgradeRelease updates release content.
	UpgradeRelease(context.Context, *UpgradeReleaseRequest) (*UpgradeReleaseResponse, error)
}

func RegisterReleaseModuleServiceServer(s *grpc.Server, srv ReleaseModuleServiceServer) {
	s.RegisterService(&_ReleaseModuleService_serviceDesc, srv)
}

func _ReleaseModuleService_InstallRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).InstallRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.modules.ReleaseModuleService/InstallRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).InstallRelease(ctx, req.(*InstallReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_DeleteRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).DeleteRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.modules.ReleaseModuleService/DeleteRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).DeleteRelease(ctx, req.(*DeleteReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_RollbackRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).RollbackRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.modules.ReleaseModuleService/RollbackRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).RollbackRelease(ctx, req.(*RollbackReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReleaseModuleService_UpgradeRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReleaseModuleServiceServer).UpgradeRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hapi.modules.ReleaseModuleService/UpgradeRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReleaseModuleServiceServer).UpgradeRelease(ctx, req.(*UpgradeReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReleaseModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hapi.modules.ReleaseModuleService",
	HandlerType: (*ReleaseModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallRelease",
			Handler:    _ReleaseModuleService_InstallRelease_Handler,
		},
		{
			MethodName: "DeleteRelease",
			Handler:    _ReleaseModuleService_DeleteRelease_Handler,
		},
		{
			MethodName: "RollbackRelease",
			Handler:    _ReleaseModuleService_RollbackRelease_Handler,
		},
		{
			MethodName: "UpgradeRelease",
			Handler:    _ReleaseModuleService_UpgradeRelease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("hapi/modules/release.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6a, 0xea, 0x40,
	0x18, 0xc5, 0xd5, 0xdc, 0x1b, 0xc9, 0xe7, 0xd5, 0x1b, 0x06, 0x63, 0x25, 0x2b, 0x19, 0x5b, 0x70,
	0x51, 0x22, 0xd8, 0x6d, 0x37, 0xad, 0x8a, 0x4a, 0x69, 0x84, 0x09, 0xa1, 0x20, 0x08, 0x8d, 0x3a,
	0xb5, 0xd2, 0xa9, 0x49, 0x33, 0x89, 0xed, 0x73, 0xf4, 0x89, 0x8b, 0xf9, 0x23, 0x4d, 0x1a, 0x2c,
	0xc5, 0xe2, 0x6e, 0xc2, 0xfc, 0x72, 0xe6, 0x3b, 0x67, 0x4e, 0x02, 0xea, 0xa3, 0xe5, 0xac, 0xda,
	0xcf, 0xf6, 0xc2, 0x67, 0x94, 0xb7, 0x5d, 0xca, 0xa8, 0xc5, 0xa9, 0xe6, 0xb8, 0xb6, 0x67, 0xa3,
	0x7f, 0xdb, 0x3d, 0x2d, 0xda, 0x53, 0x43, 0x32, 0x22, 0x92, 0x24, 0x66, 0x20, 0x12, 0xca, 0x7d,
	0xe6, 0x21, 0x04, 0x7f, 0x56, 0xeb, 0x07, 0xbb, 0x9e, 0x6f, 0xe4, 0x5b, 0x12, 0x09, 0xd6, 0x48,
	0x06, 0x81, 0xd9, 0xcb, 0x7a, 0xa1, 0x21, 0xb4, 0x24, 0xb2, 0x5d, 0xe2, 0x4b, 0x10, 0x0d, 0xcf,
	0xf2, 0x7c, 0x8e, 0x4a, 0x50, 0x34, 0xf5, 0x1b, 0x7d, 0x7c, 0xa7, 0xcb, 0xb9, 0xed, 0x83, 0x61,
	0x76, 0xbb, 0x7d, 0xc3, 0x90, 0xf3, 0xa8, 0x0c, 0x92, 0xa9, 0x77, 0x87, 0x57, 0xfa, 0xa0, 0xdf,
	0x93, 0x0b, 0x48, 0x82, 0xbf, 0x7d, 0x42, 0xc6, 0x44, 0x16, 0xf0, 0x10, 0x94, 0xd1, 0x9a, 0x7b,
	0x16, 0x63, 0x24, 0x9c, 0x82, 0xd0, 0x17, 0x9f, 0x72, 0x0f, 0xb5, 0xa1, 0x18, 0xcd, 0x15, 0x9c,
	0x5f, 0xea, 0x28, 0x5a, 0x60, 0x21, 0x1e, 0x36, 0xc6, 0x63, 0x0a, 0xbf, 0x42, 0x2d, 0xad, 0xc4,
	0x1d, 0x7b, 0xcd, 0xe9, 0x8f, 0xa5, 0xd0, 0x39, 0x88, 0x6e, 0x10, 0x41, 0xbd, 0x10, 0xf0, 0x55,
	0xed, 0x73, 0x7a, 0x5a, 0x18, 0x0f, 0x89, 0x18, 0x3c, 0x80, 0x6a, 0x8f, 0x32, 0xea, 0xd1, 0x43,
	0x1d, 0x6c, 0x40, 0x49, 0x09, 0x1d, 0xc7, 0xc0, 0x10, 0x14, 0xd3, 0x59, 0xba, 0xd6, 0x82, 0xfe,
	0xc2, 0x1d, 0xa4, 0x95, 0x8e, 0x63, 0x61, 0x04, 0x35, 0x62, 0x33, 0x36, 0xb3, 0xe6, 0x4f, 0x87,
	0x7a, 0x78, 0x83, 0x93, 0x2f, 0x52, 0x47, 0x31, 0xd1, 0x79, 0x17, 0xa0, 0x1a, 0x49, 0xdc, 0x06,
	0x84, 0x41, 0xdd, 0xcd, 0x6a, 0x4e, 0xd1, 0x14, 0x2a, 0xc9, 0x6a, 0xa3, 0x66, 0x52, 0x28, 0xf3,
	0x13, 0x52, 0x4f, 0xf7, 0x43, 0xa1, 0x29, 0x9c, 0x43, 0x13, 0x28, 0x27, 0x7a, 0x87, 0x70, 0xf2,
	0xc5, 0xac, 0x76, 0xab, 0xcd, 0xbd, 0xcc, 0x4e, 0xfb, 0x1e, 0xfe, 0xa7, 0xd2, 0x44, 0xa9, 0xb1,
	0xb2, 0xef, 0x4d, 0x3d, 0xfb, 0x86, 0xda, 0x9d, 0x30, 0x85, 0x4a, 0xb2, 0x73, 0xe9, 0x70, 0x32,
	0xbb, 0x9d, 0x0e, 0x27, 0xbb, 0xb6, 0x38, 0x77, 0x2d, 0x4d, 0xe2, 0xdb, 0x9c, 0x89, 0xc1, 0x0f,
	0xf2, 0xe2, 0x23, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xb3, 0x63, 0x07, 0x68, 0x05, 0x00, 0x00,
}
